[package]
name = "ttrpc"
version = "0.1.0"
authors = ["Hui Zhu <teawater@antfin.com>"]
edition = "2018"

[dependencies]
protobuf = { version = "2.0", optional = true }
bytes = { version = "0.4.11", optional = true }
log = "0.4"
nix = "0.14.1"
byteorder = "1.3.2"

[features]
default = ["protobuf-codec"]
protobuf-codec = ["protobuf"]

