name: BVT
on: [pull_request]
jobs:
  make:
    name: Make
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Make
        run: |
          make deps
          make

  clippy_check:
    name: Clippy Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - run: rustup component add clippy
      - uses: tim-actions/clippy-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
          name: checks-${{ matrix.os }}
